name: Task
description: General tasks (No features, bugs)
title: '[TASK]: '
labels: ['orga']
assignees: ['']

body:
- type: textarea
  id: description
  attributes:
    label: Description
    description: What has to be done?
    placeholder: Enter description...
- type: markdown
  attributes:
    value: |
        ## Defintion of Done (DoD)
        Not available yet...
- type: markdown
  attributes:
    value: |
        ## DoD General Criteria
        * Task has been fully implemented
        * Task has been merged into the mainline
        * All acceptance criteria were met
        * Product owner approved features
        * All tests are passing
        * Developers agreed to release
